# The analysis_options.yaml file is used to configure the Dart analyzer.
# For more information on configuring the analyzer, visit:
# https://dart.dev/guides/language/analysis-options

# Include recommended lints for Flutter projects
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**  # Exclude generated build files
    - .dart_tool/**  # Exclude Dart tool cache
    - example/**/generated_plugin_registrant.dart  # Exclude generated plugin files

linter:
  rules:
    # General best practices
    always_declare_return_types: true  # Ensure all functions have explicit return types
    avoid_print: true  # Avoid using print statements in production code
    prefer_final_locals: true  # Prefer using `final` for local variables
    prefer_typing_uninitialized_variables: true  # Ensure variables are properly initialized with types

    # Flutter-specific rules
    prefer_const_constructors: true  # Use const constructors where possible
    use_key_in_widget_constructors: true  # Add key parameters to custom widgets

    # Code structure and readability
    sort_constructors_first: true  # Ensure constructors are declared before other methods
    unnecessary_getters_setters: true  # Avoid unnecessary getter/setter methods

    # Documentation and API usage
    public_member_api_docs: true  # Enforce doc comments for public members
    slash_for_doc_comments: true  # Use /// for documentation comments

    # Optimization and style
    prefer_const_literals_to_create_immutables: true  # Prefer const literals for lists, maps, etc.
    prefer_final_in_for_each: true  # Use final in for-each loop declarations
    omit_local_variable_types: false  # Explicitly define types for local variables

    # Miscellaneous
    avoid_classes_with_only_static_members: true  # Avoid classes with only static members
    avoid_redundant_argument_values: true  # Avoid passing default values explicitly
    unnecessary_null_checks: true  # Avoid unnecessary null checks
